<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-09-29T13:31:20 IST" name="Suite" finished-at="2022-09-29T13:31:38 IST" duration-ms="17752">
    <groups>
    </groups>
    <test started-at="2022-09-29T13:31:20 IST" name="chromeTest" finished-at="2022-09-29T13:31:38 IST" duration-ms="17752">
      <class name="Test.TestNGClass">
        <test-method is-config="true" signature="browserLounch(java.lang.String)[pri:0, instance:Test.TestNGClass@4f18837a]" started-at="2022-09-29T13:31:21 IST" name="browserLounch" finished-at="2022-09-29T13:31:27 IST" duration-ms="6713" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- browserLounch -->
        <test-method is-config="true" signature="objectDeclare()[pri:0, instance:Test.TestNGClass@4f18837a]" started-at="2022-09-29T13:31:27 IST" name="objectDeclare" finished-at="2022-09-29T13:31:27 IST" duration-ms="106" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- objectDeclare -->
        <test-method is-config="true" signature="clickOnSignUpButton()[pri:0, instance:Test.TestNGClass@4f18837a]" started-at="2022-09-29T13:31:27 IST" name="clickOnSignUpButton" finished-at="2022-09-29T13:31:32 IST" duration-ms="4831" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clickOnSignUpButton -->
        <test-method signature="test1()[pri:0, instance:Test.TestNGClass@4f18837a]" started-at="2022-09-29T13:31:32 IST" name="test1" finished-at="2022-09-29T13:31:38 IST" duration-ms="5338" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[url is wrong expected [https://www.facebook.com/confirmemail.php?next=https%3A%2F%2Fwww.facebook.com%2F] but found [https://www.facebook.com/]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: url is wrong expected [https://www.facebook.com/confirmemail.php?next=https%3A%2F%2Fwww.facebook.com%2F] but found [https://www.facebook.com/]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at Test.TestNGClass.test1(TestNGClass.java:86)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1 -->
        <test-method is-config="true" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:Test.TestNGClass@4f18837a]" started-at="2022-09-29T13:31:38 IST" name="afterMethod" finished-at="2022-09-29T13:31:38 IST" duration-ms="294" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=test1 status=FAILURE method=TestNGClass.test1()[pri:0, instance:Test.TestNGClass@4f18837a] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method is-config="true" signature="afterClass()[pri:0, instance:Test.TestNGClass@4f18837a]" started-at="2022-09-29T13:31:38 IST" name="afterClass" finished-at="2022-09-29T13:31:38 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
        <test-method is-config="true" signature="afterTest()[pri:0, instance:Test.TestNGClass@4f18837a]" started-at="2022-09-29T13:31:38 IST" name="afterTest" finished-at="2022-09-29T13:31:38 IST" duration-ms="343" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- Test.TestNGClass -->
    </test> <!-- chromeTest -->
  </suite> <!-- Suite -->
</testng-results>
